working out alpine320 and alpine scratch

diff --git a/docker-images/5.1/nvidia2404/Dockerfile b/docker-images/5.1/nvidia2404/Dockerfile
--- a/docker-images/5.1/nvidia2404/Dockerfile
+++ b/docker-images/5.1/nvidia2404/Dockerfile
@@ -8,7 +8,7 @@
 # Stage 1: Build ( https://hub.docker.com/r/nvidia/cuda )
 FROM nvidia/cuda:12.6.2-devel-ubuntu24.04 AS builder
 
-ENV	    NVIDIA_DRIVER_CAPABILITIES compute,utility,video
+ENV	    NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
 ENV	    DEBIAN_FRONTEND=noninteractive
 
 WORKDIR     /tmp/workdir
@@ -18,14 +18,9 @@ COPY download_tarballs.sh /tmp/workdir
 COPY build_source.sh /tmp/workdir
 COPY install_ffmpeg.sh /tmp/workdir
 
-
-ENV        NVIDIA_HEADERS_VERSION=11.1.5.3
-
 ENV         ENV FFMPEG_VERSION=5.1.6
 
-# FFMPEG_VERSION=% % FFMPEG_VERSION % % \
-#    KVAZAAR_VERSION=2.3.1 \
-#    LIBVMAF_VERSION=3.0.0
+ENV NVIDIA_HEADERS_VERSION=11.1.5.3
 
 ## opencore-amr - https://sourceforge.net/projects/opencore-amr/
 ##         x264 - http://www.videolan.org/developers/x264.html
@@ -116,15 +111,15 @@ ARG LIBDRM_PKGS="libbsd0 libdrm-dev libdrm2 libxcb1-dev libxcb1"
 
 ENV MAKEFLAGS="-j2"
 ENV PKG_CONFIG_PATH="/opt/ffmpeg/share/pkgconfig:/opt/ffmpeg/lib/pkgconfig:/opt/ffmpeg/lib64/pkgconfig:/opt/ffmpeg/lib/x86_64-linux-gnu/pkgconfig:/opt/ffmpeg/lib/aarch64-linux-gnu/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig"
+
 ENV PREFIX="/opt/ffmpeg"
 ENV LD_LIBRARY_PATH="/opt/ffmpeg/lib:/opt/ffmpeg/lib64:/opt/ffmpeg/lib/aarch64-linux-gnu"
 
 
 # Note: I don't think we need 'ca-certificates'
-
 ARG DEBIAN_FRONTEND=noninteractive
 RUN     apt-get -yqq update && \
-        apt-get install -yq --no-install-recommends curl jq python3 python3-requests less tree file && \
+        apt-get install -yq --no-install-recommends curl jq python3 python3-requests less tree file vim && \
         chmod +x /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py && \
         chmod +x /tmp/workdir/download_tarballs.sh && \
         chmod +x /tmp/workdir/build_source.sh && \
@@ -166,20 +161,10 @@ RUN      buildDeps="autoconf \
                     expat \
                     libgomp1 \
                     ca-certificates \
-                    libxcb-shape0-dev" && \
+                    libxcb-shape0-dev \
+                    libavformat-dev" && \
         apt-get -yqq update && \
         apt-get install -yq --no-install-recommends ${buildDeps}
-
-# I think 'g++' is gonna get picked up in the run
-
-RUN \
-	DIR=/tmp/nv-codec-headers && \
-	git clone https://github.com/FFmpeg/nv-codec-headers ${DIR} && \
-	cd ${DIR} && \
-	git checkout n${NVIDIA_HEADERS_VERSION} && \
-	make PREFIX="${PREFIX}" && \
-	make install PREFIX="${PREFIX}" && \
-        rm -rf ${DIR}
 
 RUN \
         echo "Installing dependencies..." && \
@@ -187,29 +172,48 @@ RUN \
 
         # apt install libdrm-dev
 
-        ## libvmaf https://github.com/Netflix/vmaf
+## libvmaf https://github.com/Netflix/vmaf
+## https://github.com/Netflix/vmaf/issues/788#issuecomment-756098059
 RUN \
         echo "Adding g++ for VMAF build" && \
         apt-get install -yq g++
 
 # Note: pass '--library-list lib1,lib2,lib3 for more control.
 #       Here we have 3 libs that we have to build from source
-RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list kvazaar,libvmaf,ffmpeg
-
-## when  debugging you can pass in || true to the end of the next 3 commands
-## to keep the build going even if one of the steps fails
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list kvazaar,libvmaf
 RUN /tmp/workdir/download_tarballs.sh
-
 RUN /tmp/workdir/build_source.sh
 
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list nvidia-codec-headers
+RUN /tmp/workdir/download_tarballs.sh
+RUN /tmp/workdir/build_source.sh
+
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list ffmpeg
+RUN /tmp/workdir/download_tarballs.sh
+RUN /tmp/workdir/build_source.sh
+
+## when  debugging you can pass in || true to the end of the command
+## to keep the build going even if one of the steps fails
 RUN /tmp/workdir/install_ffmpeg.sh
 
 
 
 # Stage 2: Final Image ( shrink the size back down )
-FROM nvidia/cuda:12.6.2-devel-ubuntu24.04 AS runtime
+# FROM nvidia/cuda:12.6.2-runtime-ubuntu24.04
+FROM nvidia/cuda:12.6.2-base-ubuntu24.04 AS runtime
+# We used to use runtime, but I switched us to base, as it is significantly-smaller.
+# (~ 80Megs ) base: Includes the CUDA runtime (cudart)
+# (~ 1.4Gigs) runtime: Builds on the base and includes the CUDA math libraries⁠, and NCCL⁠.
+# (~ 4 Gigs ) devel: Builds on the runtime and includes headers, development tools for building CUDA images.
 
-ENV	    NVIDIA_DRIVER_CAPABILITIES compute,utility,video
+# COPY --from=builder /usr/local /usr/local/
+# copy only needed files, without copying nvidia dev files
+COPY --from=builder /usr/local/bin /usr/local/bin/
+COPY --from=builder /usr/local/share /usr/local/share/
+COPY --from=builder /usr/local/lib /usr/local/lib/
+COPY --from=builder /usr/local/include /usr/local/include/
+
+ENV	    NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
 ENV	    DEBIAN_FRONTEND=nonintercative
 WORKDIR     /tmp/workdir
 
@@ -217,9 +221,6 @@ RUN     apt-get -yqq update && \
         apt-get install -yq --no-install-recommends ca-certificates expat libgomp1 libxcb-shape0-dev && \
         apt-get autoremove -y && \
         apt-get clean -y
-
-
-COPY --from=builder /usr/local /usr/local/
 
 LABEL       org.opencontainers.image.authors="julien@rottenberg.info" \
             org.opencontainers.image.source=https://github.com/jrottenberg/ffmpeg
diff --git a/docker-images/6.1/vaapi2404/Dockerfile b/docker-images/6.1/vaapi2404/Dockerfile
--- a/docker-images/6.1/vaapi2404/Dockerfile
+++ b/docker-images/6.1/vaapi2404/Dockerfile
@@ -5,22 +5,18 @@
 # https://hub.docker.com/r/jrottenberg/ffmpeg/
 #
 #
-FROM        ubuntu:24.04 as base
+# Stage 1: Build
+FROM       ubuntu:24.04 AS builder
 
 WORKDIR     /tmp/workdir
 
-RUN     apt-get -yqq update && \
-        apt-get install -yq --no-install-recommends ca-certificates openssl expat libgomp1 && \
-        apt-get autoremove -y && \
-        apt-get clean -y
+COPY generate-source-of-truth-ffmpeg-versions.py /tmp/workdir
+COPY download_tarballs.sh /tmp/workdir
+COPY build_source.sh /tmp/workdir
+COPY install_ffmpeg.sh /tmp/workdir
 
-FROM base as build
 
-ENV         ENV FFMPEG_VERSION=6.1.2
-
-# FFMPEG_VERSION=% % FFMPEG_VERSION % % \
-#    KVAZAAR_VERSION=2.3.1 \
-#    LIBVMAF_VERSION=3.0.0
+ENV FFMPEG_VERSION=6.1.2
 
 ## opencore-amr - https://sourceforge.net/projects/opencore-amr/
 ##         x264 - http://www.videolan.org/developers/x264.html
@@ -111,71 +107,95 @@ ARG LIBDRM_PKGS="libbsd0 libdrm-dev libdrm2 libxcb1-dev libxcb1"
 
 ENV MAKEFLAGS="-j2"
 ENV PKG_CONFIG_PATH="/opt/ffmpeg/share/pkgconfig:/opt/ffmpeg/lib/pkgconfig:/opt/ffmpeg/lib64/pkgconfig:/opt/ffmpeg/lib/x86_64-linux-gnu/pkgconfig:/opt/ffmpeg/lib/aarch64-linux-gnu/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig"
+
 ENV PREFIX="/opt/ffmpeg"
 ENV LD_LIBRARY_PATH="/opt/ffmpeg/lib:/opt/ffmpeg/lib64:/opt/ffmpeg/lib/aarch64-linux-gnu"
 
 
 ARG DEBIAN_FRONTEND=noninteractive
 
+# Before autoremove and clean: Image was 217.01MB
+RUN     apt-get -yqq update && \
+        apt-get install -yq --no-install-recommends curl jq python3 python3-requests less tree file vim && \
+        chmod +x /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py && \
+        chmod +x /tmp/workdir/download_tarballs.sh && \
+        chmod +x /tmp/workdir/build_source.sh && \
+        chmod +x /tmp/workdir/install_ffmpeg.sh
+
 RUN      buildDeps="autoconf \
                     automake \
                     cmake \
+                    build-essential \
+                    texinfo \
                     curl \
+                    wget \
+                    tar \
                     bzip2 \
                     libexpat1-dev \
-                    g++ \
                     gcc \
                     git \
+                    git-core \
                     gperf \
                     libtool \
                     make \
                     meson \
+                    ninja-build \
                     nasm \
                     perl \
                     pkg-config \
-                    libssl-dev \
+                    python3 \
                     yasm \
+                    zlib1g-dev \
+                    libfreetype6-dev \
+                    libgnutls28-dev \
+                    libsdl2-dev \
                     libva-dev \
-                    zlib1g-dev" && \
+                    libvdpau-dev \
+                    libnuma-dev \
+                    libdav1d-dev \
+                    openssl \
+                    libssl-dev \
+                    expat \
+                    libgomp1" && \
         apt-get -yqq update && \
         apt-get install -yq --no-install-recommends ${buildDeps}
+
 RUN \
         echo "Installing dependencies..." && \
         apt-get install -yq --no-install-recommends ${OPENCORE_PKGS} ${X264_PKGS} ${X265_PKGS} ${OGG_PKGS} ${OPUS_PKGS} ${VORBIS_PKGS} ${VPX_PKGS} ${WEBP_PKGS} ${MP3LAME_PKGS} ${XVIDCORE_PKGS} ${FDKAAC_PKGS} ${OPENJP_PKGS} ${FREETYPE_PKGS} ${VIDSTAB_PKGS} ${FRIBIDI_PKGS} ${FONTCONFIG_PKGS} ${LIBASS_PKGS} ${AOM_PKGS} ${SVTAV1_PKGS} ${DAV1D_PKGS} ${XORG_MACROS_PKGS} ${XPROTO_PKGS} ${XAU_PKGS} ${PTHREADS_STUBS_PKGS} ${XML2_PKGS} ${BLURAY_PKGS} ${ZMQ_PKGS} ${PNG_PKGS} ${ARIBB24_PKGS} ${ZIMG_PKGS} ${THEORA_PKGS} ${SRT_PKGS} ${LIBDRM_PKGS}
 
+RUN \
+	apt-get install -y --no-install-recommends libva-drm2 libva2 i965-va-driver
+
         # apt install libdrm-dev
 
-        ## libvmaf https://github.com/Netflix/vmaf
+## libvmaf https://github.com/Netflix/vmaf
+## https://github.com/Netflix/vmaf/issues/788#issuecomment-756098059
 RUN \
         echo "Adding g++ for VMAF build" && \
         apt-get install -yq g++
 
 # Note: pass '--library-list lib1,lib2,lib3 for more control.
 #       Here we have 3 libs that we have to build from source
-RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list kvazaar,libvmaf,ffmpeg
-
-## when  debugging you can pass in || true to the end of the next 3 commands
-## to keep the build going even if one of the steps fails
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list kvazaar,libvmaf
 RUN /tmp/workdir/download_tarballs.sh
-
 RUN /tmp/workdir/build_source.sh
 
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list ffmpeg
+RUN /tmp/workdir/download_tarballs.sh
+RUN /tmp/workdir/build_source.sh
+
+
+## when  debugging you can pass in || true to the end of the command
+## to keep the build going even if one of the steps fails
 RUN /tmp/workdir/install_ffmpeg.sh
 
-## cleanup
-RUN \
-        ldd ${PREFIX}/bin/ffmpeg | grep opt/ffmpeg | cut -d ' ' -f 3 | xargs -i cp {} /usr/local/lib/ && \
-        for lib in /usr/local/lib/*.so.*; do ln -s "${lib##*/}" "${lib%%.so.*}".so; done && \
-        cp ${PREFIX}/bin/* /usr/local/bin/ && \
-        cp -r ${PREFIX}/share/ffmpeg /usr/local/share/ && \
-        LD_LIBRARY_PATH=/usr/local/lib ffmpeg -buildconf && \
-        cp -r ${PREFIX}/include/libav* ${PREFIX}/include/libpostproc ${PREFIX}/include/libsw* /usr/local/include && \
-        mkdir -p /usr/local/lib/pkgconfig && \
-        for pc in ${PREFIX}/lib/pkgconfig/libav*.pc ${PREFIX}/lib/pkgconfig/libpostproc.pc ${PREFIX}/lib/pkgconfig/libsw*.pc; do \
-          sed "s:${PREFIX}:/usr/local:g" <"$pc" >/usr/local/lib/pkgconfig/"${pc##*/}"; \
-        done
 
-FROM        base AS release
+
+# Stage 2: Final Image ( shrink the size back down )
+FROM ubuntu:24.04
+COPY --from=builder /usr/local /usr/local/
+
 LABEL       org.opencontainers.image.authors="julien@rottenberg.info" \
             org.opencontainers.image.source=https://github.com/jrottenberg/ffmpeg
 
@@ -183,13 +203,3 @@ ENV         LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
 
 CMD         ["--help"]
 ENTRYPOINT  ["ffmpeg"]
-
-COPY --from=build /usr/local /usr/local/
-
-RUN \
-	apt-get update -y && \
-	apt-get install -y --no-install-recommends libva-drm2 libva2 i965-va-driver && \
-	rm -rf /var/lib/apt/lists/*
-
-# Let's make sure the app built correctly
-# Convenient to verify on https://hub.docker.com/r/jrottenberg/ffmpeg/builds/ console output
diff --git a/docker-images/7.0/alpine320/Dockerfile b/docker-images/7.0/alpine320/Dockerfile
--- a/docker-images/7.0/alpine320/Dockerfile
+++ b/docker-images/7.0/alpine320/Dockerfile
@@ -4,69 +4,42 @@
 #
 #
 
-FROM        alpine:3.20 as base
+FROM        alpine:3.20 AS builder
 
-RUN         apk add --no-cache --update libgcc libstdc++ ca-certificates openssl expat git
-
-FROM        base as build
+RUN         apk add --no-cache --update libgcc libstdc++ ca-certificates openssl expat git less tree file vim bash
 
 WORKDIR     /tmp/workdir
 
-ENV         FFMPEG_VERSION=7.0.2 \
-    AOM_VERSION=v3.8.1 \
-    CHROMAPRINT_VERSION=1.5.0 \
-    FDKAAC_VERSION=0.1.5 \
-    FONTCONFIG_VERSION=2.12.4 \
-    FREETYPE_VERSION=2.10.4 \
-    FRIBIDI_VERSION=0.19.7 \
-    KVAZAAR_VERSION=2.0.0 \
-    LAME_VERSION=3.100 \
-    LIBASS_VERSION=0.13.7 \
-    LIBPTHREAD_STUBS_VERSION=0.4 \
-    LIBVIDSTAB_VERSION=1.1.0 \
-    LIBXCB_VERSION=1.13.1 \
-    XCBPROTO_VERSION=1.13 \
-    OGG_VERSION=1.3.2 \
-    OPENCOREAMR_VERSION=0.1.6 \
-    OPUS_VERSION=1.2 \
-    OPENJPEG_VERSION=2.5.2 \
-    PYTHON=python3 \
-    THEORA_VERSION=1.1.1 \
-    VORBIS_VERSION=1.3.5 \
-    VPX_VERSION=1.8.0 \
-    WEBP_VERSION=1.0.2 \
-    X264_VERSION=20191217-2245-stable \
-    X265_VERSION=4.0 \
-    XAU_VERSION=1.0.9 \
-    XORG_MACROS_VERSION=1.19.2 \
-    XPROTO_VERSION=7.0.31 \
-    XVID_VERSION=1.3.7 \
-    LIBXML2_VERSION=2.9.12 \
-    LIBBLURAY_VERSION=1.1.2 \
-    # LIBZMQ_VERSION=4.3.5 \
-    LIBSRT_VERSION=1.5.3 \
-    LIBARIBB24_VERSION=1.0.3 \
-    LIBPNG_VERSION=1.6.9 \
-    LIBVMAF_VERSION=2.3.1 \
-    ZIMG_VERSION=3.0.5 \
-    SRC=/usr/local
+COPY        generate-source-of-truth-ffmpeg-versions.py /tmp/workdir
+COPY        download_tarballs.sh /tmp/workdir
+COPY        build_source.sh /tmp/workdir
+COPY        install_ffmpeg.sh /tmp/workdir
 
-ARG         FREETYPE_SHA256SUM="5eab795ebb23ac77001cfb68b7d4d50b5d6c7469247b0b01b2c953269f658dac freetype-2.10.4.tar.gz"
-ARG         FRIBIDI_SHA256SUM="3fc96fa9473bd31dcb5500bdf1aa78b337ba13eb8c301e7c28923fea982453a8 0.19.7.tar.gz"
-ARG         LIBASS_SHA256SUM="8fadf294bf701300d4605e6f1d92929304187fca4b8d8a47889315526adbafd7 0.13.7.tar.gz"
-ARG         LIBVIDSTAB_SHA256SUM="14d2a053e56edad4f397be0cb3ef8eb1ec3150404ce99a426c4eb641861dc0bb v1.1.0.tar.gz"
-ARG         OGG_SHA256SUM="e19ee34711d7af328cb26287f4137e70630e7261b17cbe3cd41011d73a654692 libogg-1.3.2.tar.gz"
-ARG         OPUS_SHA256SUM="77db45a87b51578fbc49555ef1b10926179861d854eb2613207dc79d9ec0a9a9 opus-1.2.tar.gz"
-ARG         THEORA_SHA256SUM="40952956c47811928d1e7922cda3bc1f427eb75680c3c37249c91e949054916b libtheora-1.1.1.tar.gz"
-ARG         VORBIS_SHA256SUM="6efbcecdd3e5dfbf090341b485da9d176eb250d893e3eb378c428a2db38301ce libvorbis-1.3.5.tar.gz"
-ARG         LIBBLURAY_SHA256SUM="a3dd452239b100dc9da0d01b30e1692693e2a332a7d29917bf84bb10ea7c0b42 libbluray-1.1.2.tar.bz2"
-ARG         LIBARIBB24_SHA256SUM="f61560738926e57f9173510389634d8c06cabedfa857db4b28fb7704707ff128 v1.0.3.tar.gz"
+RUN         chmod +x /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py && \
+            chmod +x /tmp/workdir/download_tarballs.sh && \
+            chmod +x /tmp/workdir/build_source.sh && \
+            chmod +x /tmp/workdir/install_ffmpeg.sh
+
+ENV         ENV MAKEFLAGS="-j2"
+ENV PKG_CONFIG_PATH="/opt/ffmpeg/share/pkgconfig:/opt/ffmpeg/lib/pkgconfig:/opt/ffmpeg/lib64/pkgconfig:/opt/ffmpeg/lib/x86_64-linux-gnu/pkgconfig:/opt/ffmpeg/lib/aarch64-linux-gnu/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig"
+
+ENV PREFIX="/opt/ffmpeg"
+ENV LD_LIBRARY_PATH="/opt/ffmpeg/lib:/opt/ffmpeg/lib64:/opt/ffmpeg/lib/aarch64-linux-gnu"
 
 
-ARG         MAKEFLAGS="-j2"
-ARG         PKG_CONFIG_PATH="/opt/ffmpeg/share/pkgconfig:/opt/ffmpeg/lib/pkgconfig:/opt/ffmpeg/lib64/pkgconfig"
-ARG         PREFIX="/opt/ffmpeg"
-ARG         LD_LIBRARY_PATH="/opt/ffmpeg/lib:/opt/ffmpeg/lib64"
+# FFMPEG_VERSION=7.0.2 \
+#     LIBVMAF_VERSION=2.3.1 \
+#     KVAZAAR_VERSION=2.0.0 \
+#     LIBPTHREAD_STUBS_VERSION=0.4 \
+#     LIBBLURAY_VERSION=1.1.2 \
+#     LIBARIBB24_VERSION=1.0.3 \
+
+# ARG         LIBARIBB24_SHA256SUM="f61560738926e57f9173510389634d8c06cabedfa857db4b28fb7704707ff128 v1.0.3.tar.gz"
+
+# ARG         MAKEFLAGS="-j2"
+# ARG         PKG_CONFIG_PATH="/opt/ffmpeg/share/pkgconfig:/opt/ffmpeg/lib/pkgconfig:/opt/ffmpeg/lib64/pkgconfig"
+# ARG         PREFIX="/opt/ffmpeg"
+# ARG         LD_LIBRARY_PATH="/opt/ffmpeg/lib:/opt/ffmpeg/lib64"
 
 
 RUN         libDeps="libgomp \
@@ -170,7 +143,14 @@ RUN         libDeps="libgomp \
                     libpng-dev \
                     # https://github.com/sekrit-twc/zimg
                     zimg \
-                    zimg-dev" && \
+                    zimg-dev \
+                    dav1d \
+                    libdav1d \
+                    dav1d-dev \
+                    svt-av1 \
+                    svt-av1-dev \
+                    libSvtAv1Enc \
+                    libSvtAv1Dec" && \
             apk add --no-cache --update ${libDeps}
 
 
@@ -182,6 +162,8 @@ RUN     buildDeps="autoconf \
                    cmake \
                    coreutils \
                    curl \
+                   wget \
+                   jq \
                    diffutils \
                    expat-dev \
                    file \
@@ -190,174 +172,157 @@ RUN     buildDeps="autoconf \
                    gperf \
                    libtool \
                    make \
+                   meson \
+                   ninja-build \
                    nasm \
                    openssl-dev \
                    python3 \
                    tar \
+                   xz \
                    xcb-proto \
                    yasm \
                    zlib-dev \
                    alpine-sdk \
                    linux-headers" && \
         apk add --no-cache --update ${buildDeps}
-## libvmaf https://github.com/Netflix/vmaf
-RUN \
-        if which meson || false; then \
-        echo "Building VMAF." && \
-        DIR=/tmp/vmaf && \
-        mkdir -p ${DIR} && \
-        cd ${DIR} && \
-        curl -sLO https://github.com/Netflix/vmaf/archive/v${LIBVMAF_VERSION}.tar.gz && \
-        tar -xz --strip-components=1 -f v${LIBVMAF_VERSION}.tar.gz && \
-        cd /tmp/vmaf/libvmaf && \
-        meson build --buildtype release --prefix=${PREFIX} && \
-        ninja -vC build && \
-        ninja -vC build install && \
-        mkdir -p ${PREFIX}/share/model/ && \
-        cp -r /tmp/vmaf/model/* ${PREFIX}/share/model/ && \
-        rm -rf ${DIR}; \
-        else \
-        echo "VMAF skipped."; \
-        fi
+# Note: pass '--library-list lib1,lib2,lib3 for more control.
+#       Here we have 3 libs that we have to build from source
+# vmaf
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list kvazaar,libvmaf
+RUN /tmp/workdir/download_tarballs.sh
+RUN /tmp/workdir/build_source.sh
 
-## kvazaar https://github.com/ultravideo/kvazaar
-RUN \
-        DIR=/tmp/kvazaar && \
-        mkdir -p ${DIR} && \
-        cd ${DIR} && \
-        curl -sLO https://github.com/ultravideo/kvazaar/archive/v${KVAZAAR_VERSION}.tar.gz && \
-        tar -zx --strip-components=1 -f v${KVAZAAR_VERSION}.tar.gz && \
-        ./autogen.sh && \
-        ./configure --prefix="${PREFIX}" --disable-static --enable-shared && \
-        make && \
-        make install && \
-        rm -rf ${DIR}
+# # libevent && libevent-dev has usr/lib/libevent_pthreads ???
+# ## libbluray - Requires libxml, freetype, and fontconfig
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list libpthread-stubs,libbluray,libaribb24
+RUN /tmp/workdir/download_tarballs.sh
+RUN /tmp/workdir/build_source.sh
 
-# libevent && libevent-dev has usr/lib/libevent_pthreads ???
-RUN \
-        DIR=/tmp/libpthread-stubs && \
-        mkdir -p ${DIR} && \
-        cd ${DIR} && \
-        curl -sLO https://xcb.freedesktop.org/dist/libpthread-stubs-${LIBPTHREAD_STUBS_VERSION}.tar.gz && \
-        tar -zx --strip-components=1 -f libpthread-stubs-${LIBPTHREAD_STUBS_VERSION}.tar.gz && \
-        ./configure --prefix="${PREFIX}" && \
-        make && \
-        make install && \
-        rm -rf ${DIR}
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list ffmpeg
+RUN /tmp/workdir/download_tarballs.sh
+RUN /tmp/workdir/build_source.sh || true
+
+## when  debugging you can pass in || true to the end of the command
+## to keep the build going even if one of the steps fails
+RUN /tmp/workdir/install_ffmpeg.sh || true
 
 
-## libbluray - Requires libxml, freetype, and fontconfig
-RUN \
-        DIR=/tmp/libbluray && \
-        mkdir -p ${DIR} && \
-        cd ${DIR} && \
-        curl -sLO https://download.videolan.org/pub/videolan/libbluray/${LIBBLURAY_VERSION}/libbluray-${LIBBLURAY_VERSION}.tar.bz2 && \
-        echo ${LIBBLURAY_SHA256SUM} | sha256sum --check && \
-        tar -jx --strip-components=1 -f libbluray-${LIBBLURAY_VERSION}.tar.bz2 && \
-        ./configure --prefix="${PREFIX}" --disable-examples --disable-bdjava-jar --disable-static --enable-shared && \
-        make && \
-        make install && \
-        rm -rf ${DIR}
+# ## libvmaf https://github.com/Netflix/vmaf
+# RUN \
+#         if which meson || false; then \
+#         echo "Building VMAF." && \
+#         DIR=/tmp/vmaf && \
+#         mkdir -p ${DIR} && \
+#         cd ${DIR} && \
+#         curl -sLO https://github.com/Netflix/vmaf/archive/v${LIBVMAF_VERSION}.tar.gz && \
+#         tar -xz --strip-components=1 -f v${LIBVMAF_VERSION}.tar.gz && \
+#         cd /tmp/vmaf/libvmaf && \
+#         meson build --buildtype release --prefix=${PREFIX} && \
+#         ninja -vC build && \
+#         ninja -vC build install && \
+#         mkdir -p ${PREFIX}/share/model/ && \
+#         cp -r /tmp/vmaf/model/* ${PREFIX}/share/model/ && \
+#         rm -rf ${DIR}; \
+#         else \
+#         echo "VMAF skipped."; \
+#         fi
 
-## libaribb24
-RUN \
-        DIR=/tmp/b24 && \
-        mkdir -p ${DIR} && \
-        cd ${DIR} && \
-        curl -sLO https://github.com/nkoriyama/aribb24/archive/v${LIBARIBB24_VERSION}.tar.gz && \
-        echo ${LIBARIBB24_SHA256SUM} | sha256sum --check && \
-        tar -xz --strip-components=1 -f v${LIBARIBB24_VERSION}.tar.gz && \
+# ## kvazaar https://github.com/ultravideo/kvazaar
+# RUN \
+#         DIR=/tmp/kvazaar && \
+#         mkdir -p ${DIR} && \
+#         cd ${DIR} && \
+#         curl -sLO https://github.com/ultravideo/kvazaar/archive/v${KVAZAAR_VERSION}.tar.gz && \
+#         tar -zx --strip-components=1 -f v${KVAZAAR_VERSION}.tar.gz && \
+#         ./autogen.sh && \
+#         ./configure --prefix="${PREFIX}" --disable-static --enable-shared && \
+#         make && \
+#         make install && \
+#         rm -rf ${DIR}
 
-        autoreconf -fiv && \
-        ./configure CFLAGS="-I${PREFIX}/include -fPIC" --prefix="${PREFIX}" && \
-        make && \
-        make install && \
-        rm -rf ${DIR}
-
-## Download ffmpeg https://ffmpeg.org/
-RUN  \
-        DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} && \
-        curl -sLO https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
-        tar -jx --strip-components=1 -f ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
-        ./configure     --disable-debug  --disable-doc    --disable-ffplay   --enable-shared --enable-gpl  --extra-libs=-ldl && \
-        make ;  make install
-
-
-
-
-
-# ## Build ffmpeg https://ffmpeg.org/
-RUN  \
-        DIR=/tmp/ffmpeg && cd ${DIR} && \
-        ./configure \
-        --disable-debug \
-        --disable-doc \
-        --disable-ffplay \
-        --enable-fontconfig \
-        --enable-gpl \
-        --enable-libaom \
-        --enable-libaribb24 \
-        --enable-libass \
-        --enable-libbluray \
-        --enable-libdav1d \
-        --enable-libfdk-aac \
-        --enable-libfreetype \
-        --enable-libkvazaar \
-        --enable-libmp3lame \
-        --enable-libopencore-amrnb \
-        --enable-libopencore-amrwb \
-        --enable-libopenjpeg \
-        --enable-libopus \
-        --enable-libsrt \
-        --enable-libsvtav1 \
-        --enable-libtheora \
-        --enable-libvidstab \
-        --enable-libvorbis \
-        --enable-libvpx \
-        --enable-libwebp \
-        --enable-libx264 \
-        --enable-libx265 \
-        --enable-libxvid \
-        --enable-libzimg \
-        --enable-libzmq \
-        --enable-nonfree \
-        --enable-openssl \
-        --enable-postproc \
-        --enable-shared \
-        --enable-small \
-        --enable-version3 \
-        --extra-cflags="-I${PREFIX}/include" \
-        --extra-ldflags="-L${PREFIX}/lib" \
-        --extra-libs=-ldl \
-        --extra-libs=-lm \
-        --extra-libs=-lpthread \
-        --ld=g++ \
-        --prefix="${PREFIX}" && \
-        make clean && \
-        make && \
-        make install && \
-        make tools/zmqsend && cp tools/zmqsend ${PREFIX}/bin/ && \
-        make distclean && \
-        hash -r && \
-        cd tools && \
-        make qt-faststart && cp qt-faststart ${PREFIX}/bin/
+# # libevent && libevent-dev has usr/lib/libevent_pthreads ???
+# RUN \
+#         DIR=/tmp/libpthread-stubs && \
+#         mkdir -p ${DIR} && \
+#         cd ${DIR} && \
+#         curl -sLO https://xcb.freedesktop.org/dist/libpthread-stubs-${LIBPTHREAD_STUBS_VERSION}.tar.gz && \
+#         tar -zx --strip-components=1 -f libpthread-stubs-${LIBPTHREAD_STUBS_VERSION}.tar.gz && \
+#         ./configure --prefix="${PREFIX}" && \
+#         make && \
+#         make install && \
+#         rm -rf ${DIR}
 
 
-RUN \
-    ldd ${PREFIX}/bin/ffmpeg | grep opt/ffmpeg | cut -d ' ' -f 3 | xargs -i cp {} /usr/local/lib/ && \
-    for lib in /usr/local/lib/*.so.*; do ln -sf "${lib##*/}" "${lib%%.so.*}".so; done && \
-    cp ${PREFIX}/bin/* /usr/local/bin/ && \
-    cp -r ${PREFIX}/share/ffmpeg /usr/local/share/ && \
-    LD_LIBRARY_PATH=/usr/local/lib ffmpeg -buildconf && \
-    mkdir -p /usr/local/include && \
-    cp -r ${PREFIX}/include/libav* ${PREFIX}/include/libpostproc ${PREFIX}/include/libsw* /usr/local/include && \
-    mkdir -p /usr/local/lib/pkgconfig && \
-    for pc in ${PREFIX}/lib/pkgconfig/libav*.pc ${PREFIX}/lib/pkgconfig/libpostproc.pc ${PREFIX}/lib/pkgconfig/libsw*.pc; do \
-        sed "s:${PREFIX}:/usr/local:g" <"$pc" >/usr/local/lib/pkgconfig/"${pc##*/}"; \
-    done
+# ## libbluray - Requires libxml, freetype, and fontconfig
+# RUN \
+#         DIR=/tmp/libbluray && \
+#         mkdir -p ${DIR} && \
+#         cd ${DIR} && \
+#         curl -sLO https://download.videolan.org/pub/videolan/libbluray/${LIBBLURAY_VERSION}/libbluray-${LIBBLURAY_VERSION}.tar.bz2 && \
+#         echo ${LIBBLURAY_SHA256SUM} | sha256sum --check && \
+#         tar -jx --strip-components=1 -f libbluray-${LIBBLURAY_VERSION}.tar.bz2 && \
+#         ./configure --prefix="${PREFIX}" --disable-examples --disable-bdjava-jar --disable-static --enable-shared && \
+#         make && \
+#         make install && \
+#         rm -rf ${DIR}
+
+# ## libaribb24
+# RUN \
+#         DIR=/tmp/b24 && \
+#         mkdir -p ${DIR} && \
+#         cd ${DIR} && \
+#         curl -sLO https://github.com/nkoriyama/aribb24/archive/v${LIBARIBB24_VERSION}.tar.gz && \
+#         echo ${LIBARIBB24_SHA256SUM} | sha256sum --check && \
+#         tar -xz --strip-components=1 -f v${LIBARIBB24_VERSION}.tar.gz && \
+
+#         autoreconf -fiv && \
+#         ./configure CFLAGS="-I${PREFIX}/include -fPIC" --prefix="${PREFIX}" && \
+#         make && \
+#         make install && \
+#         rm -rf ${DIR}
+
+# ## Download ffmpeg https://ffmpeg.org/
+# RUN  \
+#         DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} && \
+#         curl -sLO https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
+#         tar -jx --strip-components=1 -f ffmpeg-${FFMPEG_VERSION}.tar.bz2
+#         # ./configure     --disable-debug  --disable-doc    --disable-ffplay   --enable-shared --enable-gpl  --extra-libs=-ldl && \
+#         # make ;  make install
+
+
+# # ## Build ffmpeg https://ffmpeg.org/
+# RUN  \
+#         DIR=/tmp/ffmpeg && cd ${DIR} && \
+#         ./configure \
+#         % % FFMPEG_CONFIG_FLAGS % % && \
+#         make clean && \
+#         make && \
+#         make install && \
+#         make tools/zmqsend && cp tools/zmqsend ${PREFIX}/bin/ && \
+#         make distclean && \
+#         hash -r && \
+#         cd tools && \
+#         make qt-faststart && cp qt-faststart ${PREFIX}/bin/
+
+
+# RUN \
+#     ldd ${PREFIX}/bin/ffmpeg | grep opt/ffmpeg | cut -d ' ' -f 3 | xargs -i cp {} /usr/local/lib/ && \
+#     for lib in /usr/local/lib/*.so.*; do ln -sf "${lib##*/}" "${lib%%.so.*}".so; done && \
+#     cp ${PREFIX}/bin/* /usr/local/bin/ && \
+#     cp -r ${PREFIX}/share/ffmpeg /usr/local/share/ && \
+#     LD_LIBRARY_PATH=/usr/local/lib ffmpeg -buildconf && \
+#     mkdir -p /usr/local/include && \
+#     cp -r ${PREFIX}/include/libav* ${PREFIX}/include/libpostproc ${PREFIX}/include/libsw* /usr/local/include && \
+#     mkdir -p /usr/local/lib/pkgconfig && \
+#     for pc in ${PREFIX}/lib/pkgconfig/libav*.pc ${PREFIX}/lib/pkgconfig/libpostproc.pc ${PREFIX}/lib/pkgconfig/libsw*.pc; do \
+#         sed "s:${PREFIX}:/usr/local:g" <"$pc" >/usr/local/lib/pkgconfig/"${pc##*/}"; \
+#     done
 
 ### Release Stage
-FROM        base as release
+# FROM        alpine:3.20 AS release
+# RUN         apk add --no-cache --update bash less tree file vim
+# COPY        --from=builder /usr/local /usr/local
+
 LABEL       org.opencontainers.image.authors="julien@rottenberg.info" \
             org.opencontainers.image.source=https://github.com/jrottenberg/ffmpeg
 
@@ -365,5 +330,3 @@ ENV         LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
 
 CMD         ["--help"]
 ENTRYPOINT  ["ffmpeg"]
-
-COPY --from=build /usr/local /usr/local
diff --git a/docker-images/7.1/ubuntu2404/Dockerfile b/docker-images/7.1/ubuntu2404/Dockerfile
--- a/docker-images/7.1/ubuntu2404/Dockerfile
+++ b/docker-images/7.1/ubuntu2404/Dockerfile
@@ -7,7 +7,6 @@
 #
 # Stage 1: Build
 FROM       ubuntu:24.04 AS builder
-# FROM jsheffie/ffmpeg-devel:1.0 AS builder
 
 WORKDIR     /tmp/workdir
 
@@ -18,10 +17,6 @@ COPY install_ffmpeg.sh /tmp/workdir
 
 
 ENV FFMPEG_VERSION=7.1
-
-# FFMPEG_VERSION=% % FFMPEG_VERSION % % \
-#    KVAZAAR_VERSION=2.3.1 \
-#    LIBVMAF_VERSION=3.0.0
 
 ## opencore-amr - https://sourceforge.net/projects/opencore-amr/
 ##         x264 - http://www.videolan.org/developers/x264.html
@@ -112,6 +107,7 @@ ARG LIBDRM_PKGS="libbsd0 libdrm-dev libdrm2 libxcb1-dev libxcb1"
 
 ENV MAKEFLAGS="-j2"
 ENV PKG_CONFIG_PATH="/opt/ffmpeg/share/pkgconfig:/opt/ffmpeg/lib/pkgconfig:/opt/ffmpeg/lib64/pkgconfig:/opt/ffmpeg/lib/x86_64-linux-gnu/pkgconfig:/opt/ffmpeg/lib/aarch64-linux-gnu/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig"
+
 ENV PREFIX="/opt/ffmpeg"
 ENV LD_LIBRARY_PATH="/opt/ffmpeg/lib:/opt/ffmpeg/lib64:/opt/ffmpeg/lib/aarch64-linux-gnu"
 
@@ -169,27 +165,30 @@ RUN \
 
         # apt install libdrm-dev
 
-        ## libvmaf https://github.com/Netflix/vmaf
+## libvmaf https://github.com/Netflix/vmaf
+## https://github.com/Netflix/vmaf/issues/788#issuecomment-756098059
 RUN \
         echo "Adding g++ for VMAF build" && \
         apt-get install -yq g++
 
 # Note: pass '--library-list lib1,lib2,lib3 for more control.
 #       Here we have 3 libs that we have to build from source
-RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list kvazaar,libvmaf,ffmpeg
-
-## when  debugging you can pass in || true to the end of the next 3 commands
-## to keep the build going even if one of the steps fails
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list kvazaar,libvmaf
 RUN /tmp/workdir/download_tarballs.sh
-
 RUN /tmp/workdir/build_source.sh
 
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list ffmpeg
+RUN /tmp/workdir/download_tarballs.sh
+RUN /tmp/workdir/build_source.sh
+
+## when  debugging you can pass in || true to the end of the command
+## to keep the build going even if one of the steps fails
 RUN /tmp/workdir/install_ffmpeg.sh
 
 
 
 # Stage 2: Final Image ( shrink the size back down )
-FROM ubuntu:24.04
+FROM ubuntu:24.04 AS runtime
 COPY --from=builder /usr/local /usr/local/
 
 LABEL       org.opencontainers.image.authors="julien@rottenberg.info" \
diff --git a/templates/Dockerfile-run-alpine b/templates/Dockerfile-run-alpine
--- a/templates/Dockerfile-run-alpine
+++ b/templates/Dockerfile-run-alpine
@@ -1,99 +1,118 @@
-## libvmaf https://github.com/Netflix/vmaf
-RUN \
-        if which meson || false; then \
-        echo "Building VMAF." && \
-        DIR=/tmp/vmaf && \
-        mkdir -p ${DIR} && \
-        cd ${DIR} && \
-        curl -sLO https://github.com/Netflix/vmaf/archive/v${LIBVMAF_VERSION}.tar.gz && \
-        tar -xz --strip-components=1 -f v${LIBVMAF_VERSION}.tar.gz && \
-        cd /tmp/vmaf/libvmaf && \
-        meson build --buildtype release --prefix=${PREFIX} && \
-        ninja -vC build && \
-        ninja -vC build install && \
-        mkdir -p ${PREFIX}/share/model/ && \
-        cp -r /tmp/vmaf/model/* ${PREFIX}/share/model/ && \
-        rm -rf ${DIR}; \
-        else \
-        echo "VMAF skipped."; \
-        fi
+# Note: pass '--library-list lib1,lib2,lib3 for more control.
+#       Here we have 3 libs that we have to build from source
+# vmaf
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list kvazaar,libvmaf
+RUN /tmp/workdir/download_tarballs.sh
+RUN /tmp/workdir/build_source.sh
 
-## kvazaar https://github.com/ultravideo/kvazaar
-RUN \
-        DIR=/tmp/kvazaar && \
-        mkdir -p ${DIR} && \
-        cd ${DIR} && \
-        curl -sLO https://github.com/ultravideo/kvazaar/archive/v${KVAZAAR_VERSION}.tar.gz && \
-        tar -zx --strip-components=1 -f v${KVAZAAR_VERSION}.tar.gz && \
-        ./autogen.sh && \
-        ./configure --prefix="${PREFIX}" --disable-static --enable-shared && \
-        make && \
-        make install && \
-        rm -rf ${DIR}
+# # libevent && libevent-dev has usr/lib/libevent_pthreads ???
+# ## libbluray - Requires libxml, freetype, and fontconfig
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list libpthread-stubs,libbluray,libaribb24
+RUN /tmp/workdir/download_tarballs.sh
+RUN /tmp/workdir/build_source.sh
 
-# libevent && libevent-dev has usr/lib/libevent_pthreads ???
-RUN \
-        DIR=/tmp/libpthread-stubs && \
-        mkdir -p ${DIR} && \
-        cd ${DIR} && \
-        curl -sLO https://xcb.freedesktop.org/dist/libpthread-stubs-${LIBPTHREAD_STUBS_VERSION}.tar.gz && \
-        tar -zx --strip-components=1 -f libpthread-stubs-${LIBPTHREAD_STUBS_VERSION}.tar.gz && \
-        ./configure --prefix="${PREFIX}" && \
-        make && \
-        make install && \
-        rm -rf ${DIR}
+RUN /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py --library-list ffmpeg
+RUN /tmp/workdir/download_tarballs.sh
+RUN /tmp/workdir/build_source.sh || true
+
+## when  debugging you can pass in || true to the end of the command
+## to keep the build going even if one of the steps fails
+RUN /tmp/workdir/install_ffmpeg.sh || true
 
 
-## libbluray - Requires libxml, freetype, and fontconfig
-RUN \
-        DIR=/tmp/libbluray && \
-        mkdir -p ${DIR} && \
-        cd ${DIR} && \
-        curl -sLO https://download.videolan.org/pub/videolan/libbluray/${LIBBLURAY_VERSION}/libbluray-${LIBBLURAY_VERSION}.tar.bz2 && \
-        echo ${LIBBLURAY_SHA256SUM} | sha256sum --check && \
-        tar -jx --strip-components=1 -f libbluray-${LIBBLURAY_VERSION}.tar.bz2 && \
-        ./configure --prefix="${PREFIX}" --disable-examples --disable-bdjava-jar --disable-static --enable-shared && \
-        make && \
-        make install && \
-        rm -rf ${DIR}
+# ## libvmaf https://github.com/Netflix/vmaf
+# RUN \
+#         if which meson || false; then \
+#         echo "Building VMAF." && \
+#         DIR=/tmp/vmaf && \
+#         mkdir -p ${DIR} && \
+#         cd ${DIR} && \
+#         curl -sLO https://github.com/Netflix/vmaf/archive/v${LIBVMAF_VERSION}.tar.gz && \
+#         tar -xz --strip-components=1 -f v${LIBVMAF_VERSION}.tar.gz && \
+#         cd /tmp/vmaf/libvmaf && \
+#         meson build --buildtype release --prefix=${PREFIX} && \
+#         ninja -vC build && \
+#         ninja -vC build install && \
+#         mkdir -p ${PREFIX}/share/model/ && \
+#         cp -r /tmp/vmaf/model/* ${PREFIX}/share/model/ && \
+#         rm -rf ${DIR}; \
+#         else \
+#         echo "VMAF skipped."; \
+#         fi
 
-## libaribb24
-RUN \
-        DIR=/tmp/b24 && \
-        mkdir -p ${DIR} && \
-        cd ${DIR} && \
-        curl -sLO https://github.com/nkoriyama/aribb24/archive/v${LIBARIBB24_VERSION}.tar.gz && \
-        echo ${LIBARIBB24_SHA256SUM} | sha256sum --check && \
-        tar -xz --strip-components=1 -f v${LIBARIBB24_VERSION}.tar.gz && \
+# ## kvazaar https://github.com/ultravideo/kvazaar
+# RUN \
+#         DIR=/tmp/kvazaar && \
+#         mkdir -p ${DIR} && \
+#         cd ${DIR} && \
+#         curl -sLO https://github.com/ultravideo/kvazaar/archive/v${KVAZAAR_VERSION}.tar.gz && \
+#         tar -zx --strip-components=1 -f v${KVAZAAR_VERSION}.tar.gz && \
+#         ./autogen.sh && \
+#         ./configure --prefix="${PREFIX}" --disable-static --enable-shared && \
+#         make && \
+#         make install && \
+#         rm -rf ${DIR}
 
-        autoreconf -fiv && \
-        ./configure CFLAGS="-I${PREFIX}/include -fPIC" --prefix="${PREFIX}" && \
-        make && \
-        make install && \
-        rm -rf ${DIR}
-
-## Download ffmpeg https://ffmpeg.org/
-RUN  \
-        DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} && \
-        curl -sLO https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
-        tar -jx --strip-components=1 -f ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
-        ./configure     --disable-debug  --disable-doc    --disable-ffplay   --enable-shared --enable-gpl  --extra-libs=-ldl && \
-        make ;  make install
+# # libevent && libevent-dev has usr/lib/libevent_pthreads ???
+# RUN \
+#         DIR=/tmp/libpthread-stubs && \
+#         mkdir -p ${DIR} && \
+#         cd ${DIR} && \
+#         curl -sLO https://xcb.freedesktop.org/dist/libpthread-stubs-${LIBPTHREAD_STUBS_VERSION}.tar.gz && \
+#         tar -zx --strip-components=1 -f libpthread-stubs-${LIBPTHREAD_STUBS_VERSION}.tar.gz && \
+#         ./configure --prefix="${PREFIX}" && \
+#         make && \
+#         make install && \
+#         rm -rf ${DIR}
 
 
+# ## libbluray - Requires libxml, freetype, and fontconfig
+# RUN \
+#         DIR=/tmp/libbluray && \
+#         mkdir -p ${DIR} && \
+#         cd ${DIR} && \
+#         curl -sLO https://download.videolan.org/pub/videolan/libbluray/${LIBBLURAY_VERSION}/libbluray-${LIBBLURAY_VERSION}.tar.bz2 && \
+#         echo ${LIBBLURAY_SHA256SUM} | sha256sum --check && \
+#         tar -jx --strip-components=1 -f libbluray-${LIBBLURAY_VERSION}.tar.bz2 && \
+#         ./configure --prefix="${PREFIX}" --disable-examples --disable-bdjava-jar --disable-static --enable-shared && \
+#         make && \
+#         make install && \
+#         rm -rf ${DIR}
+
+# ## libaribb24
+# RUN \
+#         DIR=/tmp/b24 && \
+#         mkdir -p ${DIR} && \
+#         cd ${DIR} && \
+#         curl -sLO https://github.com/nkoriyama/aribb24/archive/v${LIBARIBB24_VERSION}.tar.gz && \
+#         echo ${LIBARIBB24_SHA256SUM} | sha256sum --check && \
+#         tar -xz --strip-components=1 -f v${LIBARIBB24_VERSION}.tar.gz && \
+
+#         autoreconf -fiv && \
+#         ./configure CFLAGS="-I${PREFIX}/include -fPIC" --prefix="${PREFIX}" && \
+#         make && \
+#         make install && \
+#         rm -rf ${DIR}
+
+# ## Download ffmpeg https://ffmpeg.org/
+# RUN  \
+#         DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} && \
+#         curl -sLO https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
+#         tar -jx --strip-components=1 -f ffmpeg-${FFMPEG_VERSION}.tar.bz2
+#         # ./configure     --disable-debug  --disable-doc    --disable-ffplay   --enable-shared --enable-gpl  --extra-libs=-ldl && \
+#         # make ;  make install
 
 
-
-# ## Build ffmpeg https://ffmpeg.org/
-RUN  \
-        DIR=/tmp/ffmpeg && cd ${DIR} && \
-        ./configure \
-        %%FFMPEG_CONFIG_FLAGS%% && \
-        make clean && \
-        make && \
-        make install && \
-        make tools/zmqsend && cp tools/zmqsend ${PREFIX}/bin/ && \
-        make distclean && \
-        hash -r && \
-        cd tools && \
-        make qt-faststart && cp qt-faststart ${PREFIX}/bin/
+# # ## Build ffmpeg https://ffmpeg.org/
+# RUN  \
+#         DIR=/tmp/ffmpeg && cd ${DIR} && \
+#         ./configure \
+#         % % FFMPEG_CONFIG_FLAGS % % && \
+#         make clean && \
+#         make && \
+#         make install && \
+#         make tools/zmqsend && cp tools/zmqsend ${PREFIX}/bin/ && \
+#         make distclean && \
+#         hash -r && \
+#         cd tools && \
+#         make qt-faststart && cp qt-faststart ${PREFIX}/bin/
